---
# viper.tools default values

# Set values for binary links, library files (e.g. jars) and source code
viper_root: "/usr/local"
viper_bin: "{{ viper_root }}/bin"
viper_lib: "{{ viper_root }}/lib"
viper_src: "{{ viper_root }}/src"
viper_usr_share: "/usr/share"
viper_apps_share: "{{ viper_usr_share }}/applications"
viper_icons_share: "{{ viper_usr_share }}/icons"

# Account name
viper_account_name: "{{ ddhn_env_user_name | default('viper') }}"

# Tools installed via Debian package manager
viper_debian_tools:
  # Debian handbrake installation
  - "handbrake"
  # Debian Inkscape installation
  - "inkscape"
  # Debian GIMP installation
  - "gimp"

# Desktop icon files for the about to be copied to remote desktop
viper_debian_icons:
  - "org.gnome.Evince"
  - "gimp"
  - "org.inkscape.Inkscape"
  - "mediainfo-gui"
  - "mediaconch-gui"

# JHOVE version details, to override set jhove_major_minor and jhove_patch
jhove_major: "1"
jhove_minor: "26"
jhove_patch: "1"
jhove_version: "{{ jhove_major }}.{{ jhove_minor }}.{{ jhove_patch }}"

# veraPDF version details, to override set verapdf_major }}.{{ verapdf_minor and vera_patch
verapdf_major: "1"
verapdf_minor: "22"
verapdf_patch: "3"
verapdf_version: "{{ verapdf_major }}.{{ verapdf_minor }}.{{ verapdf_patch }}"

droid_major: "6"
droid_minor: "6"
droid_patch: "1"
droid_version: "{{ droid_major }}.{{ droid_minor }}.{{ droid_patch }}"

# Apache Tika version details
tika_major: "1"
tika_minor: "28"
tika_patch: "5"
tika_version: "{{ tika_major }}.{{ tika_minor }}.{{ tika_patch }}"

viper:
  tools:
    jhove:
      name: "jhove"
      desktop_name: "JHOVE GUI"
      generic_name: "Format Validation"
      comment: "Open source file format identification, validation & characterisation from The Open Preservation Foundation."
      exec: "jhove-gui"
      icon: "jhove.png"
      version: "{{ jhove_version }}"
      source:
        git: "https://github.com/openpreserve/jhove.git"
        tag: "v{{ jhove_version }}"
      installer:
        loc: "https://software.openpreservation.org/releases/jhove/{{ jhove_major }}.{{ jhove_minor }}/jhove-xplt-installer-{{ jhove_version }}.jar"
      dests:
        bin: "{{ viper_bin }}"
        lib: "{{ viper_lib }}/jhove/{{ jhove_version }}"
        src: "{{ viper_src }}/jhove/{{ jhove_version }}"
    droid:
      name: "droid"
      desktop_name: "DROID GUI"
      generic_name: "Format Identification"
      comment: "File format identification tool from The National Archives of the UK."
      exec: "droid-gui"
      icon: "droid.png"
      version: "{{ droid_version }}"
      source:
        git: "https://github.com/digital-preservation/droid.git"
        tag: "{{ droid_version }}"
      installer:
        loc: "https://repo1.maven.org/maven2/uk/gov/nationalarchives/droid-binary/{{ droid_version }}/droid-binary-{{ droid_version }}-bin.zip"
      dests:
        bin: "{{ viper_bin }}"
        lib: "{{ viper_lib }}/droid/{{ droid_version }}"
        src: "{{ viper_src }}/droid/{{ droid_version }}"
    tika:
      name: "tika"
      desktop_name: "Apache Tika GUI"
      generic_name: "Format Characterisation"
      comment: "A content analysis toolkit from the Apache Foundation."
      exec: "tika-gui"
      icon: "tika.jpg"
      version: "{{ tika_version }}"
      source:
        git: "https://github.com/apache/tika.git"
        tag: "{{ tika_version }}"
      installer:
        loc: "https://archive.apache.org/dist/tika/{{ tika_version }}/tika-app-{{ tika_version }}.jar"
      dests:
        bin: "{{ viper_bin }}"
        lib: "{{ viper_lib }}/tika/{{ tika_version }}"
        src: "{{ viper_src }}/tika/{{ tika_version }}"
    verapdf:
      name: "verapdf"
      desktop_name: "verapdf GUI"
      generic_name: "Format Validation"
      comment: "Open source, industry supported PDF/A validation from the veraPDF consortium."
      exec: "verapdf-gui"
      icon: "verapdf.png"
      version: "{{ verapdf_version }}"
      source:
        git: "https://github.com/veraPDF/veraPDF-library.git"
        tag: "v{{ verapdf_version }}"
      installer:
        loc: "https://software.verapdf.org/rel/{{ verapdf_major }}.{{ verapdf_minor }}/verapdf-greenfield-{{ verapdf_version }}-installer.zip"
        root: "/tmp/vera-installer"
        script: "/tmp/vera-installer/verapdf-greenfield-{{ verapdf_version }}/verapdf-install"
      dests:
        bin: "{{ viper_bin }}"
        lib: "{{ viper_lib }}/veraPDF/{{ verapdf_version }}"
        src: "{{ viper_src }}/veraPDF/{{ verapdf_version }}"
    mediaarea:
      - name: "libzen0v5"
        download_url: "https://mediaarea.net/download/binary/libzen0/0.4.41/libzen0v5_0.4.41-1_amd64.Debian_11.deb"
        package_name: "libzen0v5_0.4.41-1_amd64.Debian_11.deb"
      - name: "libmediainfo0v5"
        download_url: "https://mediaarea.net/download/binary/libmediainfo0/23.04/libmediainfo0v5_23.04-1_amd64.Debian_11.deb"
        package_name: "libmediainfo0v5_23.04-1_amd64.Debian_11.deb"
      - name: "libmediaconch0"
        download_url: "https://mediaarea.net/download/binary/libmediaconch0/23.03/libmediaconch0_23.03-1_amd64.Debian_11.deb"
        package_name: "libmediaconch0_23.03-1_amd64.Debian_11.deb"
      - name: "mediainfo-gui"
        download_url: "https://mediaarea.net/download/binary/mediainfo-gui/23.04/mediainfo-gui_23.04-1_amd64.Debian_11.deb"
        package_name: "mediainfo-gui_23.04-1_amd64.Debian_11.deb"
      - name: "mediaconch-gui"
        download_url: "https://mediaarea.net/download/binary/mediaconch-gui/23.03/mediaconch-gui_23.03-1_amd64.Debian_11.deb"
        package_name: "mediaconch-gui_23.03-1_amd64.Debian_11.deb"
