---
# ddhn.setup handlers

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart iptables-persistent
  service:
    name: iptables-persistent
    state: restarted

- name: rebuild locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen