---
# ddhn.tools default values

# Set values for binary links, library files (e.g. jars) and source code
ddhn_root: "/usr/local"
ddhn_bin: "{{ ddhn_root }}/bin"
ddhn_lib: "{{ ddhn_root }}/lib"
ddhn_src: "{{ ddhn_root }}/src"
ddhn_usr_share: "/usr/share"
ddhn_apps_share: "{{ ddhn_usr_share }}/applications"
ddhn_icons_share: "{{ ddhn_usr_share }}/icons"

# JHOVE version details, to override set jhove_major_minor and jhove_patch
jhove_major: "1"
jhove_minor: "24"
jhove_patch: "1"
jhove_version: "{{ jhove_major }}.{{ jhove_minor }}.{{ jhove_patch }}"

# veraPDF version details, to override set verapdf_major }}.{{ verapdf_minor and vera_patch
verapdf_major: "1"
verapdf_minor: "16"
verapdf_patch: "1"
verapdf_version: "{{ verapdf_major }}.{{ verapdf_minor }}.{{ verapdf_patch }}"

droid_major: "6"
droid_minor: "5"
droid_version: "{{ droid_major }}.{{ droid_minor }}"

# Apache Tika version details
tika_major: "1"
tika_minor: "24"
tika_patch: "1"
tika_version: "{{ tika_major }}.{{ tika_minor }}.{{ tika_patch }}"

ddhn:
  tools:
    jhove:
      name: "jhove"
      desktop_name: "JHOVE GUI"
      generic_name: "Format Validation"
      comment: "Open source file format identification, validation & characterisation from The Open Preservation Foundation."
      exec: "jhove-gui"
      icon: "jhove.png"
      version: "{{ jhove_version }}"
      source:
        git: "https://github.com/openpreserve/jhove.git"
        tag: "v{{ jhove_version }}"
      installer:
        loc: "https://software.openpreservation.org/releases/jhove/{{ jhove_major }}.{{ jhove_minor }}/jhove-xplt-installer-{{ jhove_version }}.jar"
      dests:
        bin: "{{ ddhn_bin }}"
        lib: "{{ ddhn_lib }}/jhove/{{ jhove_version }}"
        src: "{{ ddhn_src }}/jhove/{{ jhove_version }}"
    droid:
      name: "droid"
      desktop_name: "DROID GUI"
      generic_name: "Format Identification"
      comment: "File format identification tool from The National Archives of the UK."
      exec: "droid-gui"
      icon: "droid.png"
      version: "{{ droid_version }}"
      source:
        git: "https://github.com/digital-preservation/droid.git"
        tag: "droid-{{ droid_version }}"
      installer:
        loc: "https://github.com/digital-preservation/droid/releases/download/droid-{{ droid_version }}/droid-binary-{{ droid_version }}-bin.zip"
      dests:
        bin: "{{ ddhn_bin }}"
        lib: "{{ ddhn_lib }}/droid/{{ droid_version }}"
        src: "{{ ddhn_src }}/droid/{{ droid_version }}"
    tika:
      name: "tika"
      desktop_name: "Apache Tika GUI"
      generic_name: "Format Characterisation"
      comment: "A content analysis toolkit from the Apache Foundation."
      exec: "tika-gui"
      icon: "tika.jpg"
      version: "{{ tika_version }}"
      source:
        git: "https://github.com/apache/tika.git"
        tag: "{{ tika_version }}"
      installer:
        loc: "http://apache.mirror.anlx.net/tika/tika-app-{{ tika_version }}.jar"
      dests:
        bin: "{{ ddhn_bin }}"
        lib: "{{ ddhn_lib }}/tika/{{ tika_version }}"
        src: "{{ ddhn_src }}/tika/{{ tika_version }}"
    verapdf:
      name: "verapdf"
      desktop_name: "verapdf GUI"
      generic_name: "Format Validation"
      comment: "Open source, industry supported PDF/A validation from the veraPDF consortium."
      exec: "verapdf-gui"
      icon: "verapdf.png"
      version: "{{ verapdf_version }}"
      source:
        git: "https://github.com/veraPDF/veraPDF-library.git"
        tag: "v{{ verapdf_version }}"
      installer:
        loc: "https://software.verapdf.org/rel/{{ verapdf_major }}.{{ verapdf_minor }}/verapdf-greenfield-{{ verapdf_version }}-installer.zip"
        root: "/tmp/vera-installer"
        script: "/tmp/vera-installer/verapdf-greenfield-{{ verapdf_version }}/verapdf-install"
      dests:
        bin: "{{ ddhn_bin }}"
        lib: "{{ ddhn_lib }}/veraPDF/{{ verapdf_version }}"
        src: "{{ ddhn_src }}/veraPDF/{{ verapdf_version }}"
