# VIPER tools metadata
---
galaxy_info:
  author: "Carl Wilson"
  company: "Open Preservation Foundation"
  description: "ViPER tool installations."
  license: GPL v3
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - OPF
    - DDHN
    - VIPER
