# ddhn.setup metadata
---
galaxy_info:
  author: "Carl Wilson"
  company: "Open Preservation Foundation"
  description: "DDHN environment setup, accounts, pre-installs, etc."
  license: GPL v3
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - OPF
    - DDHN
